openapi: 3.0.0
info:
  title: Movya Wallet Backend API
  version: 1.0.0
  description: API for user authentication with Google OAuth.

servers:
  # Add your actual server URLs here (e.g., development, production)
  - url: http://localhost:8080 # Example local server
    description: Development server
  # - url: https://your-production-url.com
  #   description: Production server

paths:
  # Authentication (No wallet generation)
  /auth/login: # Replace with your actual login path
    post:
      summary: User Login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username: # Or email, etc.
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Authentication successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Authentication successful.
                  token: # Example JWT token
                    type: string
        '401':
          description: Invalid credentials.
        '500':
          description: Server error during authentication.

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT # Or however your token is formatted
      description: JWT token obtained after login/authentication.

tags:
  - name: Authentication
    description: User login and authentication management. 